name: divine_soul_yoga
description: "A new Flutter project."


publish_to: 'none' 
version: 1.1.1+6

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.3
  youtube_player_flutter: ^9.0.3
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.2
  pinput: ^5.0.0
  intl: ^0.19.0
  flutter_html: ^3.0.0-beta.2
  image_picker: ^1.1.2
  google_maps_flutter: ^2.10.0
  provider: ^6.1.2
  just_audio: ^0.9.18
  audio_session: ^0.1.6
  razorpay_flutter: ^1.4.0
  uuid: ^3.0.6
  flutter_inappwebview: ^6.1.5
  geolocator: ^12.0.0
  url_launcher: ^6.1.7
  change_app_package_name: ^1.4.0
  http: ^1.3.0
  permission_handler: ^11.3.1
  animated_text_kit: ^4.2.3
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  workmanager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.15.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  android_12: true
  image_path: "assets/icon/icon1.png"


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/splash/
    
  fonts:
    - family: Gotu
      fonts:
        - asset: assets/fonts/Gotu-Regular.ttf   
  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
