name: divine_soul_yoga
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.0







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.3
  youtube_player_flutter: ^9.0.3
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.2
  pinput: ^5.0.0
  intl: ^0.19.0
  flutter_html: any
  image_picker: ^1.1.2
  google_maps_flutter: ^2.10.0
  provider: ^6.1.2
  just_audio:
  audio_session:
  razorpay_flutter:
  uuid:
  flutter_inappwebview: ^6.1.5
  geolocator:
  url_launcher:
  change_app_package_name: ^1.4.0
  http: ^1.3.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.15.0


#flutter_native_splash:
#  color: "#673AB7"
#  android_12: true
#  android: true
#  image: "assets/icon/icon1.png"



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  android_12: true
  image_path: "assets/icon/icon1.png"


flutter:
  
  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/splash/
    
  fonts:
    - family: Gotu
      fonts:
        - asset: assets/fonts/Gotu-Regular.ttf   
  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
